# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
warnings_are_errors: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ppa:opencpu/imagemagick
    packages:
      - libmagick++-dev
dist:
  - xenial
branches:
  only:
  - master
  - develop
matrix:
  allow_failures:
    - os: osx
language: r
r:
  - oldrel
  - release
  - devel
cache:
  packages: true
sudo: false
install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - Rscript -e "devtools::install_github('jimhester/covr')"
r_check_args: --as-cran
after_success:
  - Rscript -e 'covr::codecov()'
